<div class="row header_title">
    <h2 class="header_text">Where to Buy</h2>
</div>
<main class="content">
          <div class="row">
            <a>Here's where you can find out nearest iconik Outlet,countrywide. You can search by City and Location.</a>
        </div>
        <div class="row">
            <div class="col-md-6">
                <form class="col-md-12">
                    <fieldset >
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" checked>
                            <label class="form-check-label" for="flexRadioDefault1">
                                Search by city
                            </label>
                        </div>  
                      <div class="mb-3">
                        <label for="disabledSelect" class="form-label">Select Your City*</label>
                        <select id="disabledSelect" class="form-select">
                          <option>Disabled select</option>
                          <option>Disabled select</option>
                          <option>Disabled select</option>
                          <option>Disabled select</option>
                          <option>Disabled select</option>
                        </select>
                      </div>
                      <button type="submit" class="btn btn-dark">Search City <i class="bi bi-caret-right-fill"></i></button>
                    </fieldset>
                  </form>
            </div>
            <div class="col-md-6">
                <form class="col-md-12">
                    <fieldset >
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" >
                            <label class="form-check-label" for="flexRadioDefault1">
                                Search by Location
                            </label>
                        </div>  
                      <div class="mb-3">
                        <label for="disabledSelect" class="form-label">Enter Your Location</label>
                        <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Input your location here...">
                      </div>
                      <button type="submit" class="btn btn-dark">Search Location <i class="bi bi-caret-right-fill"></i></button>
                    </fieldset>
                  </form>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-5">
                <div class="mapouter">
                    <div class="gmap_canvas">
                        <iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=Pennsylvania%20Station&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                        <a href="https://www.whatismyip-address.com/elementor/">elementor pro discount</a><br>
                        <style>.mapouter{position:relative;text-align:right;height:500px;width:100%;}</style>
                        <a href="https://www.embedgooglemap.net"></a>
                        <style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:100%;}</style>
                    </div>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
        
        <hr>
        <div class="row">
            <h5>All Outlet Address and Phone Numbers</h5>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12 left-city">
                        <h5>Calofornia</h5>
                        <p>Lorem Ipsum has been the industry's standard dummy text ever, TEL: 1300 00 00</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 left-city">
                        <h5>Washinton, DC</h5>
                        <p>Lorem Ipsum has been the industry's standard dummy text ever, TEL: 1300 00 00</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 left-city">
                        <h5>Alaska</h5>
                        <p>Lorem Ipsum has been the industry's standard dummy text ever, TEL: 1300 00 00</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12 right-city">
                        <h5>New York</h5>
                        <p>Lorem Ipsum has been the industry's standard dummy text ever, TEL: 1300 00 00</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 right-city">
                        <h5>Vergenia</h5>
                        <p>Lorem Ipsum has been the industry's standard dummy text ever, TEL: 1300 00 00</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 right-city">
                        <h5>Florida</h5>
                        <p>Lorem Ipsum has been the industry's standard dummy text ever, TEL: 1300 00 00</p>
                    </div>
                </div>
            </div>
        </div>
      </main>