<div class="header_title">
    <h2 class="header_text">Connect with Iconik</h2>
</div>
<main class="contents">
  <div class="row grid_container social">
    <div class="col-md-4 grid-item fb">
      <p>connect with facebook</p>
      <a href="#" target="_blank"> <span class="bi bi-github"></span></a>
      <p><b>24,840 Fans</b>/Join Me</p>
    </div>
    <div class="col-md-4 grid-item tweet">
      <p>connect with twitter</p>
      <a href="#" target="_blank"><span class="bi bi-facebook"></span></a>
      <p><b>30,785 Fans</b>/Tweet Me</p>
    </div>
    <div class="col-md-4 grid-item google">
      <p>connect with google plus</p>
      <a href="#" target="_blank"><span class="bi bi-google"></span></a>
      <p><b>15,650 Fans</b>/Follow Me</p>
    </div>

  </div>

  <div class="form-container">
    <hr>
    <h6 class="second_heading">Coonect with iconik by sending Email</h6>
    <form>
  <div class="row form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Your Full Name</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Your Email Address</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
    </div>
  </div>
  <div class="row form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Confirm Email Address</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Telephone Number</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Query (Max 500 words)</label>
    <textarea class="form-control" aria-label="With textarea"></textarea>
  </div>

  <button type="submit" class="btn btn-dark btn-query">Send Query<i class="bi bi-play-fill"></i></button>
</form>

  </div>
  </main>