<div class="col-md-3 footer_item">
        <p class="para">Lookbook</p>
        <ul class="footer-links">
            <li><a href="#">Sun Production</a></li>
            <li><a href="#">Collection 2014</a></li>
            <li><a href="#">Optical Collection</a></li>
            <li><a href="#">Jack + Jack Collection</a></li>
            <li><a href="#">Kate Sylvester</a></li>
        </ul>
    </div>
    <div class="col-md-3 footer_item">
        <p class="para">Company Info</p>
        <ul class="footer-links ">
            <li><a href="#">Retailers</a></li>
            <li><a href="#">Editorials</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">Career With Iconik </a></li>
        </ul>
    </div>
    <div class="col-md-3 footer_item">
        <p class="para">General Info</p>
        <ul class="footer-links">
            <li><a href="#">Terms of Use</a></li>
            <li><a href="#">Iconik Friends</a></li>
            <li><a href="#">Sitemap</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Security Service</a></li>
        </ul>
    </div>
    <div style="clear: both;"></div>
    
