<div class="social-links">
    <p class="social_text">Stay Connected with</p>
    <ul class="links">
        <li><a href="#"><i class="uil uil-facebook-f"></i></a></li>
        <li><a href="#"><i class="uil uil-twitter"></i></a></li>
        <li><a href="#"><i class="uil uil-google"></i></a></li>
        <li><a href="#"><i class="uil uil-vuejs"></i></a></li>
    </ul>
    <p class="social_text">Sign Up With Our Newsletter</p>
</div>
<div style="clear: both;"></div>