
<div class="row second_sec">
    <p class="ad-text">Each Iconik eyewear frame in our collection has been personally selected by a South Melbourne Optical eyewear fashion consultant who is also profesionally trained to select and fit the perfect spectacle lens for your prescription on site.</p>
    

    <div class="img-container">
        <hr class="break-line">
            <div class="left-img-container">
                <div class="image-container row">
                    <div class="left-img upper-img">
                        <img src="<?= $block->getViewFileUrl('images/girlOne.jpg'); ?>" alt="Girl in a jacket" width="200" height="200"/>
                    </div>
                    <div class="right-img upper-img">
                        <img src="<?= $block->getViewFileUrl('images/menOne.jpg'); ?>" alt="Girl in a jacket" width="200" height="200"/>
                    </div>
                </div>
                <div class="image-container row">
                    <div class="left-img lower-img">
                        <img src="<?= $block->getViewFileUrl('images/girlTwo.jpeg'); ?>" alt="Girl in a jacket" width="200" height="200"/>
                    </div>
                    <div class="right-img lower-img">
                        <img src="<?= $block->getViewFileUrl('images/menTwo.jpg'); ?>" alt="Girl in a jacket" width="200" height="200"/>
                    </div>
                </div>
            </div>
            <div class="right-img-container"><img src="<?= $block->getViewFileUrl('images/glasess.png'); ?>" alt="Girl in a jacket"/></div>
        <div style="clear: both;"></div>
        <hr class="break-line">
    </div>
</div>


<div class="heading">

	<h4>ICONIK COLLECTION</h4>
		<div class="product data items"
		data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 1, "disabled": [3], "disabledState": "disabled"}}'>
			<div class="item title tab_title" data-role="collapsible">
				<a class="switch tab_link all_tab_link" data-toggle="trigger" href="#tab-collection-one">Optical Collection</a>
			</div>
			<div id="tab-collection-one" class="item content productSlider" data-role="content"><div id="mageplaza-productslider-block-after-content-1">    <div class="mp-product-slider-block block widget block-products-list grid">
        <h2 class="mp-product-slider-title">Optical Collection</h2>
        <p class="mp-ps-info"></p>
    </div>
    <div class="block-content mp-product-slider-content">
        <div class="products-grid grid">
            <ol class="product-items widget-viewed-grid">
                                <div id="mp-list-items-1-6128d5b2369dc" class="owl-carousel owl-theme owl-loaded owl-drag">
                                                                                <div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-2580px, 0px, 0px); transition: all 0.25s ease 0s; width: 4300px;"><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/blair-black.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/1/e1399a1a1_1_lar_1.jpg" max-width="240" max-height="300" alt="Blair Black"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Blair Black" href="http://localhost/m2project/blair-black.html">
                                        Blair Black                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2048" data-price-box="product-id-2048">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2048-widget-product-grid" data-price-amount="20" data-price-type="finalPrice" class="price-wrapper "><span class="price">$20.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/black-mate.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/f/t/ft1053a1a1-from-fastrack-500x500.png" max-width="240" max-height="300" alt="Black Mate"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Black Mate" href="http://localhost/m2project/black-mate.html">
                                        Black Mate                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2049" data-price-box="product-id-2049">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2049-widget-product-grid" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper "><span class="price">$25.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/gray-black.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/f/t/ft1018c1a1-from-fastrack-500x500.png" max-width="240" max-height="300" alt="Gray Black"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Gray Black" href="http://localhost/m2project/gray-black.html">
                                        Gray Black                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2050" data-price-box="product-id-2050">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2050-widget-product-grid" data-price-amount="10" data-price-type="finalPrice" class="price-wrapper "><span class="price">$10.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                        </li></div><div class="owl-item" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/grca-dark-brown.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/1/e1399a1a1_1_lar.jpg" max-width="240" max-height="300" alt="Grca Dark Brown"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Grca Dark Brown" href="http://localhost/m2project/grca-dark-brown.html">
                                        Grca Dark Brown                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047" data-price-box="product-id-2047">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2047-widget-product-grid" data-price-amount="10" data-price-type="finalPrice" class="price-wrapper "><span class="price">$10.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/blair-black.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/1/e1399a1a1_1_lar_1.jpg" max-width="240" max-height="300" alt="Blair Black"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Blair Black" href="http://localhost/m2project/blair-black.html">
                                        Blair Black                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2048" data-price-box="product-id-2048">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2048-widget-product-grid" data-price-amount="20" data-price-type="finalPrice" class="price-wrapper "><span class="price">$20.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/black-mate.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/f/t/ft1053a1a1-from-fastrack-500x500.png" max-width="240" max-height="300" alt="Black Mate"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Black Mate" href="http://localhost/m2project/black-mate.html">
                                        Black Mate                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2049" data-price-box="product-id-2049">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2049-widget-product-grid" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper "><span class="price">$25.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/gray-black.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/f/t/ft1018c1a1-from-fastrack-500x500.png" max-width="240" max-height="300" alt="Gray Black"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Gray Black" href="http://localhost/m2project/gray-black.html">
                                        Gray Black                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2050" data-price-box="product-id-2050">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2050-widget-product-grid" data-price-amount="10" data-price-type="finalPrice" class="price-wrapper "><span class="price">$10.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                        </li></div><div class="owl-item cloned active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/grca-dark-brown.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/1/e1399a1a1_1_lar.jpg" max-width="240" max-height="300" alt="Grca Dark Brown"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Grca Dark Brown" href="http://localhost/m2project/grca-dark-brown.html">
                                        Grca Dark Brown                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2047" data-price-box="product-id-2047">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2047-widget-product-grid" data-price-amount="10" data-price-type="finalPrice" class="price-wrapper "><span class="price">$10.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/blair-black.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/1/e1399a1a1_1_lar_1.jpg" max-width="240" max-height="300" alt="Blair Black"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Blair Black" href="http://localhost/m2project/blair-black.html">
                                        Blair Black                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2048" data-price-box="product-id-2048">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2048-widget-product-grid" data-price-amount="20" data-price-type="finalPrice" class="price-wrapper "><span class="price">$20.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/black-mate.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/f/t/ft1053a1a1-from-fastrack-500x500.png" max-width="240" max-height="300" alt="Black Mate"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Black Mate" href="http://localhost/m2project/black-mate.html">
                                        Black Mate                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2049" data-price-box="product-id-2049">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2049-widget-product-grid" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper "><span class="price">$25.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div></div></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots disabled"></div></div>
            </ol>
        </div>
            </div>
    <script>
        require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
            $('#mp-list-items-1-6128d5b2369dc').owlCarousel({loop:true,margin:10,nav:true,dots:false,lazyLoad:false,autoplay:true,autoplayTimeout:5000,autoplayHoverPause:true,});
        });
    </script>

</div></div>

            <!-- End One -->

			<div class="item title tab_title" data-role="collapsible">
				<a class="switch tab_link" data-toggle="trigger" href="#tab-collection-two">Collection 2014</a>
			</div>
			<div id="tab-collection-two" class="item content productSlider" data-role="content"><div id="mageplaza-productslider-block-after-content-2">    <div class="mp-product-slider-block block widget block-products-list grid">
        <h2 class="mp-product-slider-title">Collection 2014</h2>
        <p class="mp-ps-info"></p>
    </div>
    <div class="block-content mp-product-slider-content">
        <div class="products-grid grid">
            <ol class="product-items widget-viewed-grid">
                                <div id="mp-list-items-2-6128d5b2f102f" class="owl-carousel owl-theme owl-loaded owl-drag">
                                                                                <div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-1290px, 0px, 0px); transition: all 0.25s ease 0s; width: 4300px;"><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/orange.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/c/ece67944171be5965638904de8d869bbfd1745359cffcc1357681194fa52cd3c.jpg" max-width="240" max-height="300" alt="Orange"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Orange" href="http://localhost/m2project/orange.html">
                                        Orange                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2052" data-price-box="product-id-2052">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2052-widget-product-grid" data-price-amount="12" data-price-type="finalPrice" class="price-wrapper "><span class="price">$12.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/classic.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/7/e7aa394c64064557b71c5b585c839b25.jpg" max-width="240" max-height="300" alt="Classic"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Classic" href="http://localhost/m2project/classic.html">
                                        Classic                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2053" data-price-box="product-id-2053">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2053-widget-product-grid" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper "><span class="price">$13.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/classic-bold.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/i/m/image2.jpeg" max-width="240" max-height="300" alt="Classic Bold"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Classic Bold" href="http://localhost/m2project/classic-bold.html">
                                        Classic Bold                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2054" data-price-box="product-id-2054">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2054-widget-product-grid" data-price-amount="15" data-price-type="finalPrice" class="price-wrapper "><span class="price">$15.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                        </li></div><div class="owl-item active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/yellow.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/y/eye-respect-2.jpg" max-width="240" max-height="300" alt="Yellow"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Yellow" href="http://localhost/m2project/yellow.html">
                                        Yellow                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2051" data-price-box="product-id-2051">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2051-widget-product-grid" data-price-amount="15" data-price-type="finalPrice" class="price-wrapper "><span class="price">$15.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/orange.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/c/ece67944171be5965638904de8d869bbfd1745359cffcc1357681194fa52cd3c.jpg" max-width="240" max-height="300" alt="Orange"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Orange" href="http://localhost/m2project/orange.html">
                                        Orange                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2052" data-price-box="product-id-2052">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2052-widget-product-grid" data-price-amount="12" data-price-type="finalPrice" class="price-wrapper "><span class="price">$12.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/classic.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/7/e7aa394c64064557b71c5b585c839b25.jpg" max-width="240" max-height="300" alt="Classic"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Classic" href="http://localhost/m2project/classic.html">
                                        Classic                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2053" data-price-box="product-id-2053">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2053-widget-product-grid" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper "><span class="price">$13.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/classic-bold.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/i/m/image2.jpeg" max-width="240" max-height="300" alt="Classic Bold"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Classic Bold" href="http://localhost/m2project/classic-bold.html">
                                        Classic Bold                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2054" data-price-box="product-id-2054">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2054-widget-product-grid" data-price-amount="15" data-price-type="finalPrice" class="price-wrapper "><span class="price">$15.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                        </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/yellow.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/y/eye-respect-2.jpg" max-width="240" max-height="300" alt="Yellow"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Yellow" href="http://localhost/m2project/yellow.html">
                                        Yellow                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2051" data-price-box="product-id-2051">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2051-widget-product-grid" data-price-amount="15" data-price-type="finalPrice" class="price-wrapper "><span class="price">$15.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/orange.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/c/ece67944171be5965638904de8d869bbfd1745359cffcc1357681194fa52cd3c.jpg" max-width="240" max-height="300" alt="Orange"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Orange" href="http://localhost/m2project/orange.html">
                                        Orange                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2052" data-price-box="product-id-2052">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2052-widget-product-grid" data-price-amount="12" data-price-type="finalPrice" class="price-wrapper "><span class="price">$12.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/classic.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/e/7/e7aa394c64064557b71c5b585c839b25.jpg" max-width="240" max-height="300" alt="Classic"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Classic" href="http://localhost/m2project/classic.html">
                                        Classic                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2053" data-price-box="product-id-2053">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2053-widget-product-grid" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper "><span class="price">$13.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div></div></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots disabled"></div></div>
            </ol>
        </div>
            </div>
    <script>
        require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
            $('#mp-list-items-2-6128d5b2f102f').owlCarousel({loop:true,margin:10,nav:true,dots:false,lazyLoad:false,autoplay:true,autoplayTimeout:5000,autoplayHoverPause:true,});
        });
    </script>

</div></div>

            <!-- End Two -->

			<div class="item title tab_title" data-role="collapsible">
				<a class="switch tab_link" data-toggle="trigger" href="#tab-collection-three">Sun Protection</a>
			</div>
			<div id="tab-collection-three" class="item content productSlider" data-role="content"><div id="mageplaza-productslider-block-after-content-3">    <div class="mp-product-slider-block block widget block-products-list grid">
        <h2 class="mp-product-slider-title">Sun Protection</h2>
        <p class="mp-ps-info"></p>
    </div>
    <div class="block-content mp-product-slider-content">
        <div class="products-grid grid">
            <ol class="product-items widget-viewed-grid">
                                <div id="mp-list-items-3-6128d5b324d8f" class="owl-carousel owl-theme owl-loaded owl-drag">
                                                                                <div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-1720px, 0px, 0px); transition: all 0.25s ease 0s; width: 3870px;"><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-blue.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/s/u/sun.jpeg" max-width="240" max-height="300" alt="Sun Blue"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Blue" href="http://localhost/m2project/sun-blue.html">
                                        Sun Blue                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2056" data-price-box="product-id-2056">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2056-widget-product-grid" data-price-amount="20" data-price-type="finalPrice" class="price-wrapper "><span class="price">$20.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-gray.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/s/u/sun3.jpeg" max-width="240" max-height="300" alt="Sun Gray"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Gray" href="http://localhost/m2project/sun-gray.html">
                                        Sun Gray                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2058" data-price-box="product-id-2058">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2058-widget-product-grid" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper "><span class="price">$25.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-brown.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/g/o/gogals_images3.jpg" max-width="240" max-height="300" alt="Sun Brown"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Brown" href="http://localhost/m2project/sun-brown.html">
                                        Sun Brown                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2059" data-price-box="product-id-2059">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2059-widget-product-grid" data-price-amount="10" data-price-type="finalPrice" class="price-wrapper "><span class="price">$10.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                        </li></div><div class="owl-item" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-blue.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/s/u/sun.jpeg" max-width="240" max-height="300" alt="Sun Blue"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Blue" href="http://localhost/m2project/sun-blue.html">
                                        Sun Blue                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2056" data-price-box="product-id-2056">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2056-widget-product-grid" data-price-amount="20" data-price-type="finalPrice" class="price-wrapper "><span class="price">$20.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-gray.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/s/u/sun3.jpeg" max-width="240" max-height="300" alt="Sun Gray"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Gray" href="http://localhost/m2project/sun-gray.html">
                                        Sun Gray                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2058" data-price-box="product-id-2058">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2058-widget-product-grid" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper "><span class="price">$25.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-brown.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/g/o/gogals_images3.jpg" max-width="240" max-height="300" alt="Sun Brown"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Brown" href="http://localhost/m2project/sun-brown.html">
                                        Sun Brown                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2059" data-price-box="product-id-2059">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2059-widget-product-grid" data-price-amount="10" data-price-type="finalPrice" class="price-wrapper "><span class="price">$10.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                        </li></div><div class="owl-item cloned active" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-blue.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/s/u/sun.jpeg" max-width="240" max-height="300" alt="Sun Blue"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Blue" href="http://localhost/m2project/sun-blue.html">
                                        Sun Blue                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2056" data-price-box="product-id-2056">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2056-widget-product-grid" data-price-amount="20" data-price-type="finalPrice" class="price-wrapper "><span class="price">$20.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-gray.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/s/u/sun3.jpeg" max-width="240" max-height="300" alt="Sun Gray"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Gray" href="http://localhost/m2project/sun-gray.html">
                                        Sun Gray                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2058" data-price-box="product-id-2058">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2058-widget-product-grid" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper "><span class="price">$25.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                                                                    </li></div><div class="owl-item cloned" style="width: 420px; margin-right: 10px;"><li class="product-item product-slider" "="">                        <div class="slider-product-item-info">
                            <a href="http://localhost/m2project/sun-brown.html" class="product photo slider-product-item-photo">
                                
<span class="product-image-container" style="width:240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="http://localhost/m2project/pub/media/catalog/product/cache/19e6f7ba0c639702852eeb2ef0a85377/g/o/gogals_images3.jpg" max-width="240" max-height="300" alt="Sun Brown"></span>
</span>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="Sun Brown" href="http://localhost/m2project/sun-brown.html">
                                        Sun Brown                                    </a>
                                </strong>

                                
                                
                                                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="2059" data-price-box="product-id-2059">
    

<span class="price-container price-final_price tax weee">
        <span id="old-price-2059-widget-product-grid" data-price-amount="10" data-price-type="finalPrice" class="price-wrapper "><span class="price">$10.00</span></span>
        </span>

</div>                                
                                <div class="product actions slider-product-item-actions product-item-actions">
                                                                    </div>
                            </div>
                        </div>
                        </li></div></div></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots disabled"></div></div>
            </ol>
        </div>
            </div>
    <script>
        require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
            $('#mp-list-items-3-6128d5b324d8f').owlCarousel({loop:true,margin:10,nav:true,dots:false,lazyLoad:false,autoplay:true,autoplayTimeout:5000,autoplayHoverPause:true,});
        });
    </script>

</div></div>
            <!-- End Three -->
</div>
</div>
 
 <div class="third-section">
 	<div class="first-item">
 		<img src="<?= $block->getViewFileUrl('images/banner-girl.jpg'); ?>" alt="Girl in a jacket"/>
 	</div>
 	<div class="second-item">
 		<img src="<?= $block->getViewFileUrl('images/single-glass.png'); ?>" alt="Girl in a jacket"/>
 		<p>
			As a premium International and Australian brand. Iconik eyeglasses are available <br> in many styles and colour  combinations for both male and female customers <br> at South Melbourne Optical.
		</p>
		<button class="discover"> Discover Sun Protection <i class="uil uil-caret-right"></i></button>
 	</div>
 	<div class="third-item">
 		
 	</div>
 	
 	<div style="clear: both;"></div>
	
</div>

<div class="img-section">
	<div class="writings">
		<p>
			As a premium International and Australian brand. Iconik eyeglasses are available <br> in many styles and colour  combinations for both male and female customers <br> at South Melbourne Optical.
		</p>
		<button class="contact"> Contact Our Retailer <i class="uil uil-caret-right"></i></button>
	</div>
	<div class="img-content">
		<img src="<?= $block->getViewFileUrl('images/glass-cover.png'); ?>" alt="Girl in a jacket"/>
	</div>
</div>

	




