<div class="row header_title">
    <h2 class="header_text">The Iconik Story</h2>
</div>
<main class="image-content">
        <div class="img-banner">
            <img src="<?= $block->getViewFileUrl('Iconik_Story::images/picOne.png'); ?>" alt="Image One">
        </div>
    
    
        <div class="img-banner">
            <img src="<?= $block->getViewFileUrl('Iconik_Story::images/picTwo.png'); ?>" alt="Image Two">
        </div>
    
    
        <div class="img-banner">
            <img src="<?= $block->getViewFileUrl('Iconik_Story::images/picFour.png'); ?>" alt="Image Three">
        </div>
    
    
        <div class="img-banner">
            <img src="<?= $block->getViewFileUrl('Iconik_Story::images/picThree.png'); ?>" alt="Image Four">
        </div>
      </main>